notifications:
  email: false

language: rust
rust: stable

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script:
  - docker exec -it emscripten git clone https://github.com/gfx-rs/gfx
  - git -C gfx checkout pre-ll
  - cargo build --manifest-path=gfx/Cargo.toml --example=triangle --target=asmjs-unknown-emscripten
